/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import funciones.func_ProdCate;

/**
 *
 * @author CESAR
 */
public class Inter_Agre_Marca extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_Agre_Marca
     * 
     */
    func_ProdCate obj_func_ProdCate;
    public Inter_Agre_Marca() {
        initComponents();
        obj_func_ProdCate=new func_ProdCate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_codigo_marca = new javax.swing.JTextField();
        txt_nombre_marca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_descripcion_marca = new javax.swing.JTextArea();
        btn_grabar_marca = new javax.swing.JButton();

        setClosable(true);
        setTitle("AGREGAR MARCA");

        jLabel1.setText("Codigo de  Marca");

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripcion");

        area_descripcion_marca.setColumns(20);
        area_descripcion_marca.setRows(5);
        jScrollPane1.setViewportView(area_descripcion_marca);

        btn_grabar_marca.setText("AGREGAR");
        btn_grabar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabar_marcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txt_nombre_marca)
                    .addComponent(txt_codigo_marca)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_grabar_marca)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codigo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_grabar_marca)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_grabar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabar_marcaActionPerformed
        // TODO add your handling code here:
        String codigo=txt_codigo_marca.getText();
        String nombre=txt_nombre_marca.getText();
        String descripcion=area_descripcion_marca.getText();
        //getters_setters
        
        //fin getters_setters
        obj_func_ProdCate.InsertarMarca(codigo, nombre, descripcion);
        //borrando...
        txt_codigo_marca.setText("");
        txt_nombre_marca.setText("");
        area_descripcion_marca.setText("");
        
    }//GEN-LAST:event_btn_grabar_marcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_descripcion_marca;
    private javax.swing.JButton btn_grabar_marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_codigo_marca;
    private javax.swing.JTextField txt_nombre_marca;
    // End of variables declaration//GEN-END:variables
}
