/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import funciones.func_tien;
import getters_setters.tienda_Getters_Setters;

/**
 *
 * @author NAVARRO
 */
public class Inter_Agre_Sede extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_Agre_Sede
     */
    func_tien obj_func_tien;
    public Inter_Agre_Sede() {
        initComponents();
         
        
       
        
    }
    public void LLenarElCombo(){
        obj_func_tien=new func_tien();
        obj_func_tien.ConsultaTienda(combo_tienda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_codigo_sede = new javax.swing.JTextField();
        txt_denominacion_sede = new javax.swing.JTextField();
        txt_direccion_sede = new javax.swing.JTextField();
        txt_telefono_sede = new javax.swing.JTextField();
        txt_correo_sede = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo_tienda = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btn_grabar_sede = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_cancelar_sede = new javax.swing.JButton();

        setClosable(true);
        setTitle("AGREGAR SEDE");

        jLabel4.setText("Telefono");

        jLabel5.setText("Correo");

        jLabel6.setText("Entidad");

        jLabel1.setText("Codigo Sede");

        combo_tienda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Denominacion");

        btn_grabar_sede.setText("Grabar");
        btn_grabar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabar_sedeActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion");

        btn_cancelar_sede.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(txt_codigo_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addComponent(txt_telefono_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_denominacion_sede)
                            .addComponent(txt_direccion_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_grabar_sede)
                        .addGap(42, 42, 42)
                        .addComponent(btn_cancelar_sede))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_correo_sede)
                            .addComponent(combo_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_codigo_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_denominacion_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_direccion_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_telefono_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_correo_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_grabar_sede)
                    .addComponent(btn_cancelar_sede)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_grabar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabar_sedeActionPerformed
        // TODO add your handling code here:
        //recuperamos los datos...
        String codigo=txt_codigo_sede.getText();
        String denominacion=txt_denominacion_sede.getText();
        String direccion=txt_direccion_sede.getText();
        String telefono=txt_telefono_sede.getText();
        String correo=txt_correo_sede.getText();
        
                                
        tienda_Getters_Setters obj_tien_getters_setters=new tienda_Getters_Setters();
        obj_tien_getters_setters.setCodigo(codigo);
        obj_tien_getters_setters.setNombre(denominacion);
        obj_tien_getters_setters.setDireccion(direccion);
        obj_tien_getters_setters.setTelefono(telefono);
        obj_tien_getters_setters.setCorreo(correo);
        
        //insertando datos...
        obj_func_tien.InsertarSucursal(obj_tien_getters_setters.getCodigo(),obj_tien_getters_setters.getNombre(),
                obj_tien_getters_setters.getDireccion(),obj_tien_getters_setters.getTelefono(),obj_tien_getters_setters.getCorreo());
        
        
        
    }//GEN-LAST:event_btn_grabar_sedeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar_sede;
    private javax.swing.JButton btn_grabar_sede;
    private javax.swing.JComboBox combo_tienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_codigo_sede;
    private javax.swing.JTextField txt_correo_sede;
    private javax.swing.JTextField txt_denominacion_sede;
    private javax.swing.JTextField txt_direccion_sede;
    private javax.swing.JTextField txt_telefono_sede;
    // End of variables declaration//GEN-END:variables
}
